---
version: "3.5"

services:
  dev:
    build:
      context: .
      # args:
      #   ARG_DEVPI_SERVER_VERSION: ${DOCKER_DEVPI_SERVER_VERSION}
      #   ARG_DEVPI_WEB_VERSION: ${DOCKER_DEVPI_WEB_VERSION}
      #   ARG_DEVPI_CLIENT_VERSION: ${DOCKER_DEVPI_CLIENT_VERSION}
    image: okomestudio/devpi:test

