#!/usr/bin/env bash
# set -ex


: ${DEVPISERVER_PORT="3141"}
: ${DEVPISERVER_RESTRICT_MODIFY="root"}
: ${DEVPISERVER_SERVERDIR="/data/server"}

export DEVPISERVER_PORT
export DEVPISERVER_RESTRICT_MODIFY
export DEVPISERVER_SERVERDIR


function init() {
  echo "[RUN] Initialize devpi server"
  devpi-server --start --host 127.0.0.1 --init

  devpi use http://localhost:$DEVPISERVER_PORT
  devpi login root --password=''
  devpi user -m root password="${DEVPI_ROOT_PASSWORD}"
  devpi index -y -c public pypi_whitelist='*'

  devpi-server --stop
}


function main() {
  if [ ! -f $DEVPISERVER_SERVERDIR/.serverversion ]; then
    init
  fi
  exec devpi-server --host 0.0.0.0
}


if [ "$1" == "devpi-server" ]; then
  main
else
  exec "$@"
fi
